### ISSUE TITLE
HomeKit -> SignalK

### ISSUE THREAD

**Issue by BatOutOfHeck** [Krillle/homebridge-signalk#12]
Would it be possible to push HomeKit data back to SignalK? Then I could take advantage of my HomeKit (NetAtmo) weather station, contact sensors, etc... on my MFDs/SignalK apps.

Thanks so much for this great plugin.

**Comment by Krillle** [comment]
Homebridge is unfortunately not implementing a" back to the source" channel. So while it is possible in general for sure, my plugin can't do it. 

Happy to hear you using my plugin. Out of curiosity, would you share a screenshot of your Home App, showing which devices of your boat you see?
