### ISSUE TITLE
No issue but question

### ISSUE THREAD

**Issue by MarceljjVonk** [Krillle/homebridge-signalk#13]
Hi, can I use the ikommunicate as my signal k server or do I have to change settings which can not be done by this device and is it better to install this on an RP ?

**Comment by Krillle** [comment]
The homebridge plug-in needs to access the Signal K API. As long as the API is reachable on an iKommunicate it should work out. 

You can set IP address and port of your Signal K server in the configuration, e.g.:
"host": "127.0.0.1:3000"

Let me know if it works.
